joint_ids_map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 
  17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
step_dt: 0.02
stiffness: [100.0, 100.0, 100.0, 150.0, 40.0, 40.0, 100.0, 100.0, 100.0, 150.0, 40.0, 40.0, 200.0, 200.0, 200.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0]
damping: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0, 2.0, 2.0, 2.0, 4.0, 2.0, 2.0, 5.0, 5.0, 5.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

default_joint_pos: [-0.10, 0.00, 0.00, 0.30, -0.20, 0.00, -0.10, 0.00, 0.00, 0.30, -0.20, 0.00, 0.00, 0.00, 0.00, 0.30, 0.25, 0.00, 0.97, 0.15, 0.00, 0.00, 0.30, -0.25, 0.00, 0.97, -0.15, 0.00, 0.00]
commands:
  base_velocity:
    ranges:
      lin_vel_x: [-2.0, 3.0]
      lin_vel_y: [-1.0, 1.0]
      ang_vel_z: [-3.14, 3.14]
      heading: null
actions:
  JointPositionAction:
    clip: null
    joint_names: [.*]
    scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
      0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
      0.25, 0.25, 0.25, 0.25]
    offset: [-0.10, 0.00, 0.00, 0.30, -0.20, 0.00, -0.10, 0.00, 0.00, 0.30, -0.20, 0.00, 0.00, 0.00, 0.00, 0.30, 0.25, 0.00, 0.97, 0.15, 0.00, 0.00, 0.30, -0.25, 0.00, 0.97, -0.15, 0.00, 0.00]
    joint_ids: null
observations:
  base_ang_vel:
    params: {}
    clip: null
    scale: [0.25, 0.25, 0.25]
    history_length: 1
  projected_gravity:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  velocity_commands:
  # keyboard_velocity_commands:
    params: {command_name: base_velocity}
    clip: null
    scale: [2.0, 2.0, 0.25]
    history_length: 1
  joint_pos_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
      1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  joint_vel_rel:
    params: {}
    clip: null
    scale: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
      0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
      0.05, 0.05, 0.05, 0.05]
    history_length: 1
  last_action:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
      1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
