joint_ids_map: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 
  17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
step_dt: 0.02
stiffness: [40.179, 99.098, 40.179, 99.098, 28.501, 28.501, 40.179, 99.098, 40.179, 99.098, 28.501, 28.501, 40.179, 28.501, 28.501, 14.251, 14.251, 14.251, 14.251, 
  14.251, 16.778, 16.778, 14.251, 14.251, 14.251, 14.251, 14.251, 16.778, 16.778]
damping: [2.558, 6.309, 2.558, 6.309, 1.814, 1.814, 2.558, 6.309, 2.558, 6.309, 1.814, 1.814, 2.558, 1.814, 1.814, 0.907, 0.907, 0.907, 0.907,
 0.907, 1.068, 1.068, 0.907, 0.907, 0.907, 0.907, 0.907, 1.068, 1.068]
default_joint_pos: [-0.312, 0.000, 0.000, 0.669, -0.363, 0.000, -0.312, 0.000, 0.000, 0.669, -0.363, 0.000, 0.000, 0.000, 0.000, 0.200, 0.200, 0.000, 
  0.600, 0.000, 0.000, 0.000, 0.200, -0.200, 0.000, 0.600, 0.000, 0.000, 0.000]
commands:
  base_velocity:
    ranges:
      lin_vel_x: [-1.0, 2.0]
      lin_vel_y: [-1.0, 1.0]
      ang_vel_z: [-1.0, 1.0]
      heading: null
actions:
  JointPositionAction:
    clip: null
    joint_names: [.*]
    scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
      0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
      0.25, 0.25, 0.25, 0.25]
    offset: [-0.312, 0.000, 0.000, 0.669, -0.363, 0.000, -0.312, 0.000, 0.000, 0.669, -0.363, 0.000, 0.000, 0.000, 0.000, 0.200, 0.200, 0.000, 
      0.600, 0.000, 0.000, 0.000, 0.200, -0.200, 0.000, 0.600, 0.000, 0.000, 0.000]
    joint_ids: null
observations:
  base_ang_vel:
    params: {}
    clip: null
    scale: [0.25, 0.25, 0.25]
    history_length: 1
  projected_gravity:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  velocity_commands:
  # keyboard_velocity_commands:
    params: {command_name: base_velocity}
    clip: null
    scale: [2.0, 2.0, 0.25]
    history_length: 1
  joint_pos_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
      1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  joint_vel_rel:
    params: {}
    clip: null
    scale: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
      0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
      0.05, 0.05, 0.05, 0.05]
    history_length: 1
  last_action:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
      1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
