joint_ids_map: [3,4,5,0,1,2,9,10,11,6,7,8]
step_dt: 0.02
stiffness: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]
damping: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
default_joint_pos: [0.0,  0.72,  -1.44, 
                 0.0,  0.72,  -1.44, 
                0.0,  0.72,  -1.44, 
                0.0,  0.72,  -1.44]
commands:
  base_velocity:
    ranges:
      lin_vel_x: [-1.0, 1.0]
      lin_vel_y: [-1.0, 1.0]
      ang_vel_z: [-1.57, 1.57]
      heading: null
actions:
  JointPositionAction:
    clip: null
    joint_names: [.*]
    scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
    offset: [-0.0,  0.72,  -1.44, 
                 0.0,  0.72,  -1.44, 
                -0.0,  0.72,  -1.44, 
                0.0,  0.72,  -1.44]
    joint_ids: null
observations:
  base_ang_vel:
    params: {}
    clip: null
    scale: [0.25, 0.25, 0.25]
    history_length: 5
  projected_gravity:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 5
  velocity_commands:
  # keyboard_velocity_commands:
    params: {command_name: base_velocity}
    clip: null
    scale: [2.0, 2.0, 0.25]
    history_length: 5
  joint_pos_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 5
  joint_vel_rel:
    params: {}
    clip: null
    scale: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    history_length: 5
  last_action:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 5
  gait_state:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 5
